name: docker-check

on:
    workflow_dispatch:
    push:
        branches:
            - "feature/**"

permissions:
    contents: write

jobs:
    docker-check:
        name: docker-check
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            # - name: Docker lint
            #   uses: hadolint/hadolint-action@v3.1.0
            #   with:
            #     recursive: true
            #     failure-threshold: warning

            - name: Docker format
              run: |
                  curl -fsSL https://dprint.dev/install.sh | sh -s  > /dev/null 2>&1
                  echo "/home/runner/.dprint/bin" >> $GITHUB_PATH
                  ~/.dprint/bin/dprint check
                  ~/.dprint/bin/dprint fmt