name: docker-check

on: workflow_dispatch

jobs:
    docker-lint:
        name: docker-lint
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Docker lint
              uses: hadolint/hadolint-action@v3.1.0
              with:
                recursive: true
                failure-threshold: warning